[build]
  command = "npm run netlify-build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_SKIP_TYPE_CHECK = "1"
  NEXT_SKIP_LINT = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "./netlify/plugins/prisma-build-plugin"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
